name: Scala CI

on:
  push:
    branches: [ circleci-project-setup ]
  pull_request:
    branches: [ circleci-project-setup ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
